import { Routes } from '@angular/router';
import { LoginScreen } from './login-screen/login-screen';
import { ErrorScreen } from './error-screen/error-screen';
import { HomeScreen } from './home-screen/home-screen';
import { EquipmentScreen } from './equipment-screen/equipment-screen';
import { CreateEquipmentScreen } from './create-equipment-screen/create-equipment-screen';
import { CustomerScreen } from './customer-screen/customer-screen';
import { RentalsScreen } from './rentals-screen/rentals-screen';
import { RentalDetailScreen } from './rental-detail-screen/rental-detail-screen';
import { RentalIssueScreen } from './create-rental-screen/rental-issue-screen';
import { RentalReturnScreen } from './return-rental-screen/rental-return-screen';
import { RentalEditScreen } from './edit-rental-screen/rental-edit-screen';
import { OverdueRentalsScreen } from './overdue-rentals-screen/overdue-rentals-screen';
import { AvailableScreen } from './available-screen/available-screen';
import { CreateCustomerScreen } from './create-customer-screen/create-customer-screen';
import { EditCustomerScreen } from './edit-customer-screen/edit-customer-screen';
import { CustomerDetailScreen } from './customer-detail-screen/customer-detail-screen';
import { EditEquipmentScreen } from './edit-equipment-screen/edit-equipment-screen';
import { EquipmentDetailScreen } from './equipment-detail-screen/equipment-detail-screen';

export const routes: Routes = [
  { path: 'login', component: LoginScreen },
  { path: 'home', component: HomeScreen },
  { path: 'all-equipments', component: EquipmentScreen },
  { path: 'add-equipment', component: CreateEquipmentScreen },
  { path: 'edit-equipment/:id', component: EditEquipmentScreen },
  { path: 'equipment-detail/:id', component: EquipmentDetailScreen },
  { path: 'all-customers', component: CustomerScreen },
  { path: 'add-customer', component: CreateCustomerScreen },
  { path: 'edit-customer/:id', component: EditCustomerScreen },
  { path: 'customer-detail/:id', component: CustomerDetailScreen },
  { path: 'all-rentals', component: RentalsScreen },
  { path: 'rental-detail/:id', component: RentalDetailScreen },
  { path: 'add-rental', component: RentalIssueScreen },
  { path: 'return-rental/:id', component: RentalReturnScreen },
  { path: 'edit-rental/:id', component: RentalEditScreen },
  { path: 'overdue-rentals', component: OverdueRentalsScreen },
  { path: 'available', component: AvailableScreen },
  { path: 'error', component: ErrorScreen },
  { path: '', redirectTo: '/login', pathMatch: 'full' },
];
